### ISSUE TITLE
Last update borked

### ISSUE THREAD

**Issue by fiiim** [termux/termux-tasker#9] opened 2017-09-20 06:42 UTC
After last play store update of this app, none of the tasker tasks containing the termux plugin works until you reenter the script files name. And the scripts seems to run start slower too

**Comment by loial** [comment] 2017-09-26 17:54
I can confirm that upgrading to v0.2 made existing task fail silently, until scripts were reselected.

As for timing, I made myself a script that send an intent to Tasker, to launches this plugin, with a script that ends original script.

Ran on my Nexus 6P (Nougat 7.1.1) before upgrade:

$ time .termux/tasker/termux-tasker-test.sh
new session
7287 Still running
Killed

real    0m0.759s
user    0m0.543s
sys     0m0.120s

New run after upgrade:
$ time .termux/tasker/termux-tasker-test.sh                             new session
12588 Still running
Killed

real    0m0.948s
user    0m0.690s
sys     0m0.163s

So, hardly noticable on my hardware, but might be worse on older/lower-end hardware?

**Comment by agnostic-apollo** [comment] 2020-12-16 01:27
In the version `0.2` [commit](https://github.com/TheNothingMan/termux-tasker/commit/ff23faa7fba9d8291ef06cc06551c33d79a7fe96), a check was added [if (!bundle.containsKey(EXTRA_ARGUMENTS))](https://github.com/TheNothingMan/termux-tasker/blob/ff23faa7fba9d8291ef06cc06551c33d79a7fe96/app/src/main/java/com/termux/tasker/PluginBundleManager.java#L61) which did not consider backward compatibility, and the intent was [silently ignored](https://github.com/TheNothingMan/termux-tasker/blob/ff23faa7fba9d8291ef06cc06551c33d79a7fe96/app/src/main/java/com/termux/tasker/FireReceiver.java#L35) by the `FireReceiver`, breaking it for everyone until they reconfigured their plugin which would have caused the arguments field to be added. This is the likely cause of the issue of course, `logcat` should have been checked.

**Comment by agnostic-apollo** [comment] 2021-02-14 11:21
Closing since not applicable anymore.

**Closed by agnostic-apollo** 2021-02-14 11:21 UTC
