### ISSUE TITLE
Timeout Issue with Automate

### ISSUE THREAD

**Issue by KevWal** [termux/termux-tasker#33] opened 2020-06-18 10:16 UTC
**Problem description**
I have an issue using the Termux Tasker plugin with Automate around timeouts. If the Termux command completes in less than 10 seconds it is fine, but if not it fails.

Error log:
01-21 11:30:13.290 I 58@1: Flow beginning 01-21 11:30:13.291 I 58@2: Plug-in action 01-21 11:30:13.368 D 58@2: PlugInSetting ACTION_FIRE_SETTING: resultCode=3 01-21 11:30:13.369 D 58@2: Starting 10000 ms timeout, as requested 01-21 11:30:23.388 F 58@2: java.util.concurrent.TimeoutException: Plug-in didn't respond within requested timeout 01-21 11:30:23.390 I 58@2: Stopped by failure

**Steps to reproduce**
Create a new Automate flow, add a termux task that takes longer than 10 seconds to execute.

**Expected behaviour**
The ability to set, or remove the timeout

**Additional information**

* Termux application version:  1.22.1
* Android OS version: 10
* Device model: Samsung Galaxy S10+

See comments from Automate author here:

https://old.reddit.com/r/AutomateUser/comments/erthy2/automate_termux_timeout_issue/

**Comment by Archenoth** [comment] 2020-11-09 20:46
Hihi! I'm the one who put that default there, and while I'm not sure how to set it from Automate, there is indeed an option for setting the timeouts in Tasker~ (10 seconds is just the default value the plugin suggests initially--so don't worry, it's not a hardcoded limit!)

![A screenshot of termux-tasker's configuration screen allowing the configuration of timeouts](https://user-images.githubusercontent.com/1385527/98592921-a5aa4800-228f-11eb-8f8d-3599c1b9e78c.png)

The reason for a 10 second default was because most actions are pretty quick--and if something took that long, it was just less annoying to let someone set that time to a bigger number rather than force someone to wait longer if they accidentally did something that would never stop.

[This post is was made too long ago for me to reply to](https://old.reddit.com/r/AutomateUser/comments/erthy2/automate_termux_timeout_issue/ff7vbnx/), and I'm not really affiliated with Tasker or anyone else that can change how this all works, but the suggested timeout from the plugin should be in the `net.dinglisch.android.tasker.extras.REQUESTED_TIMEOUT` extra in the intent sent to Tasker after configuration. (After which, you have the ability to override it in Tasker itself--but if you can't override it in Automate, then perhaps you have the ability to at least change that extra before it gets there)

**Comment by KevWal** [comment] 2020-11-09 22:18
Thank you for getting back to me on this one.

I still have the issue so will take a look through your sugestions tomorrow. 

Cheers
Kevin

On 9 November 2020 20:47:02 GMT, Archenoth <notifications@github.com> wrote:
>Hihi! I'm the one who put that default there, and while I'm not sure
>how to set it from Automate, there is indeed an option for setting the
>timeouts in Tasker~ (10 seconds is just the default value the plugin
>suggests initially--so don't worry, it's not a hardcoded limit!)
>
>![A screenshot of termux-tasker's configuration screen allowing the
>configuration of
>timeouts](https://user-images.githubusercontent.com/1385527/98592921-a5aa4800-228f-11eb-8f8d-3599c1b9e78c.png)
>
>The reason for a 10 second default was because most actions are pretty
>quick--and if something took that long, it was just less annoying to
>let someone set that time to a bigger number rather than force someone
>to wait longer if they accidentally did something that would never
>stop.
>
>[This post is was made too long ago for me to reply
>to](https://old.reddit.com/r/AutomateUser/comments/erthy2/automate_termux_timeout_issue/ff7vbnx/),
>and I'm not really affiliated with Tasker or anyone else that can
>change how this all works, but the suggested timeout from the plugin
>should be in the
>`net.dinglisch.android.tasker.extras.REQUESTED_TIMEOUT` extra in the
>intent sent to Tasker after configuration. (After which, you have the
>ability to override it in Tasker itself--but if you can't override it
>in Automate, then perhaps you have the ability to at least change that
>extra before it gets there)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-tasker/issues/33#issuecomment-724268683

-- 
Sent from my Android device. Please excuse my brevity.

**Comment by Archenoth** [comment] 2020-11-09 23:40
Hey! Happy to help!

And sorry for the extremely long delay--I'm not actually part of the core Termux team or anything, so it was just kinda random chance that I saw this issue. But yeah! I don't think the issue is a plugin one.

Tasker plugins suggest default values for things that are configured in Tasker itself--and `timeout` just happens to be one of those options.

If you'd like a stop-gap fix in the meantime, if Automate can run based on received intents, you could make your script fork into a background process. Then, when it finishes, have it run:

```sh
am broadcast -a net.dinglish.tasker.continue
```

And then listen for that in your task continuation and continue!

---

For a more permanent solution, I would recommend suggesting a feature request for Automate to allow configuring the suggested values that plugins return for things like timeout.

You can even include a link to this issue, since it has some information that might be handy for handling Tasker plugins--since I imagine this might be an issue for others as well!

**Comment by agnostic-apollo** [comment] 2020-12-16 02:12
Termux:Tasker only "requests" a default timeout, which is now `10s` for all cases in version [0.5](https://github.com/termux/termux-tasker/releases/tag/v0.5). Check number `9` in Issue [36](https://github.com/termux/termux-tasker/pull/36) for details. The user can still override it from the plugin host side, even though commands themselves are not directly affected by any timeout set. Automate app was however considering it as a literal timeout instead of a request, but has provided a [Ignore Timeout](https://llamalab.com/automate/doc/block/plugin_setting.html) option in version [1.23.1](https://forums.androidcentral.com/android-apps/436693-app-4-0-automate-automatic-tasks-3.html).

So this issue should be considered as solved, even though a "no timeout" can be sent back only in the case if plugin action is being configured by the Automate app, if the devs and users think that would be better. Would this be the value `0`? Although, the Tasker way IMO is better since it provides the user more control, specially with `Continue Task Immediately` behaviour.

Automate app should also request the permission `com.termux.permission.RUN_COMMAND` for the plugin to work in version `>= 0.5`. Check the updated [README](https://github.com/termux/termux-tasker) for more information.

**Comment by agnostic-apollo** [comment] 2021-09-11 14:27
Since no default timeout for Automate has been suggested, closing this.

Related fecba503

**Closed by agnostic-apollo** 2021-09-11 14:27 UTC
